package com.froilan.synectix.model.enums.product;

public enum WarehouseType {
    DISTRIBUTION_CENTER,
    REGIONAL_WAREHOUSE,
    FULFILLMENT_CENTER,
    COLD_STORAGE,
    CROSS_DOCKING_FACILITY,
    BULK_STORAGE_WAREHOUSE,
    AUTOMATED_WAREHOUSE,
    RETAIL_WAREHOUSE,
    MANUFACTURING_WAREHOUSE,
    PUBLIC_WAREHOUSE,
    PRIVATE_WAREHOUSE,
    VIRTUAL_WAREHOUSE
}
